[project]
name = "bioinfo-project-frfr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "marimo>=0.11.26",
    "numpy>=2.2.4",
    "polars>=1.26.0",
    "torch>=2.6.0",
]
